### ISSUE TITLE
uninitialized variable

### ISSUE THREAD

**Issue by maddin200** [OpenMRI/ocra#82]
Applications/shim_controller/shim_controller_test.c line 230
Code:
 void *cfg, *sts;
vs
 rx_cntr = ((uint16_t *)(sts + 0));

**Comment by marcman86** [comment]
Hi, for what are you using the code?

This code is one of the oldest versions of OCRA.

Please use the ocra/applications/relax2 python GUI and its server.

**Comment by maddin200** [comment]
deprecated
